FROM postgres:12.14
#LABEL maintainer = "Manan"
#ADD target/AuthenticationProject-0.0.1-SNAPSHOT.jar AuthenticationProject.jar
#ENTRYPOINT["Java" , "-jar" , "AuthenticationProject.jar"]
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD password
ENV POSTGRES_DB postgresDatabase

