version: '2'

services:

  ctomcat:
    build:
      context: .
      dockerfile: ./docker/tomcat/Dockerfile
    ports:
      - "8080:8080"
    image: itomcat-user-registration


  cpostgres:
    build:
      context: "./docker/postgres"
    ports:
      - "5432:5432"
    restart: always
    image: ipostgres-user-registration